---
- hosts: test
  become: true
  tasks:
   - name: Backup splunk etc directory
     archive:
       path: /opt/splunk/etc
       dest: /opt/splunk_etc.tar.gz
       format: gz
       
  
   - name: Copy the Splunk Enterprise tar file to /opt
     copy:
        src: splunk-9.1.3-d95b3299fa65-Linux-x86_64.tgz
        dest: /opt

   - name: Stop Splunk Service
     become_user: splunk
     command: /opt/splunk/bin/splunk stop

   - name: Extract splunk tar to /opt
     ansible.builtin.unarchive:
        src: /opt/splunk-9.1.3-d95b3299fa65-Linux-x86_64.tgz
        dest: /opt
        remote_src: yes

   - name: chown to splunk directory
     file:
       path: /opt/splunk
       owner: splunk
       group: splunk
       recurse: yes

   - name: Start Splunk service
     become_user: splunk
     command: /opt/splunk/bin/splunk start --accept-license --answer-yes
     
